### PR TITLE
Added RHEL 7 support

### PR DESCRIPTION
**Pull request by retr0h**

### CODE REVIEW

**Comment by retr0h** [comment]
@tersmitten interested?

**Comment by tersmitten** [comment]
Thanks for your contribution. However I'd rather not add extra complexity for platforms we don't use (and test). I have more than 75 roles to maintain and that's quite time consuming.

I will add a `CONTRIBUTING.md` stating the above.

If you really want me to merge the pull request I will do so (it does not add much complexity), but if you have no objections working with a fork I'd rather have it that way.

I hope you understand my reasons and let me how you want to proceed.

**Comment by retr0h** [comment]
@tersmitten Oh, I understand.  I'll tell you why I submitted the patch.  We ended up writing a keepalived role, and it actually ended up looking fairly similar to yours.  A few iterations further, and it looked a little too similar.  Our functionality is identical to yours with the exception of the RH package.

I was attempting to "do the right thing", by contributing to a well established role.  For the benefit of others, not just myself.

**Comment by tersmitten** [comment]
Fair enough, I'll merge it. I'm in the mood for "doing the right thing" :-)

**Pull request merged**
