### PR TITLE
add become statement to role use example in readme

### PR DESCRIPTION
**Pull request by jantari**
Hello,

thanks for your work on this module.

When trying it out I started with the example in the README.md,
however I immediately got a permission denied error on the first task (`allow binding non-local IP`)
because the individual tasks in the role do not specify `become` where needed.

Therefore, it is necessary to use the entire role with a blanket `become: yes` statement.
This was not in the example previously, so it didn't work as-is.

This is just a small correction so people can get started faster with your role, nobody likes red text in the console 😉

### CODE REVIEW

**Comment by tersmitten** [comment]
>Therefore, it is necessary to use the entire role with a blanket `become: yes` statement.

Isn't that the case for most roles?

**Comment by tersmitten** [comment]
I prefer to keep it like this. 

Consistent with all the other roles

**Comment by jantari** [comment]
hmm I understand you want to keep it consistent but what about the argument that it literally *doesn't work* the way it is shown in the example though?

**Comment by tersmitten** [comment]
>but what about the argument that it _literally_ doesn't work

Works fine for me, without `become: yes`

**Comment by jantari** [comment]
Are you using root as your ansible_user then?

**Comment by tersmitten** [comment]
Yes, I think so

**Comment by jantari** [comment]
Well then obviously you don't need an explicit `become: yes` in your lab environment.

However you will not find this setup in any organization or most peoples' home environments as use of the `root` user is commonly restricted to disaster recovery scenarios only because it breaks auditability. You can no longer audit which employee made a change when everyone is just sharing an account (`root`). In addition to the auditing requirements, disallowing remote `root` login is mandated by most basic security compliance frameworks, checklists and audits (e.g. [STIG V-72247](https://www.stigviewer.com/stig/red_hat_enterprise_linux_7/2017-12-14/finding/V-72247))

So I understand if you prefer to continue to use `root` in your dev environment to manage what are presumably effectively single-user machines anyway, but imo writing examples with the expectation of your users' environments being the same may be misguided as most prefer to have even their dev and test environments match the configuration of prod, with proper auditability and a resemblance of basic security even where not strictly mandated by law or compliance requirements specific to an industry.

What I'm saying is, the vast majority of people will have to elevate privileges through `become` when deploying this role through their individual user accounts.

**Pull request closed without merging**
